.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. safecoin_qt test_safecoin_qt
clean: FORCE
	$(MAKE) -C .. safecoin_qt_clean test_safecoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_safecoin_qt_check
safecoin-qt safecoin-qt.exe: FORCE
	 $(MAKE) -C .. safecoin_qt
