#!/bin/bash

# Minimum number of UTXOs to maintain
TARGETAMNT=10

splitexec=~/safecoin/src/splitfunds

print_txid () {
  txid=$(echo $1 | jq -r .txid)
  if [[ $txid = "" ]]; then
    echo -n "No valid UTXO to split"
  else
    echo -n $txid
  fi
}

# Amount of UTXOs to create at one time
splitamount () {
  SPLITAMNT=$(( $TARGETAMNT -$2 ))
}

#Print Date and Time
now=$(date +"%Y-%m-%d %T%z")
echo $now

echo "Checking SAFE"
cd ~

echo -n SAFE
UTXOS="$(safecoin-cli listunspent | grep -c .00010000)"
echo -n -e '\t\t';echo -n "$UTXOS"
if [ "$UTXOS" -lt "25" ]
   then
     SPLITAMNT=$(( 50 -$UTXOS ))
     echo -n " - SPLITFUNDING SAFE: "
     RESULT="$($splitexec $1)"
     print_txid $RESULT
   fi
echo ""

echo "--------------------------------------------------------------------------------------------------"
echo "running cron on splitcron to maintain split utxos"
echo "--------------------------------------------------------------------------------------------------"
bash ~/safecoin/src/splitcron &
