name: safecoin  # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.9 + git' # just for humans, typically '1.2+git' or '1.3.2'
summary: SafeCoin daemon # 79 char long summary
description: |
  This will install just the SafeCoin command line wallet build.  Use 'safecoin' to run the wallet and 'safecoin.cli' plus a cli command to 
  use command line wallet tools.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  openssl:
    plugin: nil
    source: https://www.openssl.org/source/openssl-1.0.1j.tar.gz
    build-packages:
      - g++
      - build-essential
      - libtool
    override-build: |
      echo "Downgrading OpenSSL to 1.0.1j"
      sudo ./config
      sudo make
      echo "Make depends OpenSSL to 1.0.1j"
      sudo make depend
      echo "Make install OpenSSL to 1.0.1j"
      sudo make install
      echo "Linking OpenSSL to 1.0.1j"
      sudo ln -sf /usr/local/ssl/bin/openssl `which openssl`
  safecoin:
    # See 'snapcraft plugins'
    plugin: nil
    source: .
    build-packages:
      - build-essential
      - pkg-config
      - libc6-dev
      - m4
      - g++-multilib
      - autoconf
      - libtool
      - ncurses-dev
      - unzip
      - git
      - python
      - python-zmq
      - zlib1g-dev
      - wget
      - libcurl4-gnutls-dev
      - bsdmainutils
      - automake
      - curl
      - bc 
      - dc 
      - jq
      - libboost-all-dev
    stage-packages:
      - build-essential
      - pkg-config
      - libc6-dev
      - m4
      - g++-multilib
      - autoconf
      - libtool
      - ncurses-dev
      - unzip
      - git
      - python
      - python-zmq
      - zlib1g-dev
      - wget
      - libcurl4-gnutls-dev
      - bsdmainutils
      - automake
      - curl
      - bc 
      - dc 
      - jq
      - libboost-all-dev
    override-build: |
      OPENSSL_INCLUDE_PATH=/usr/local/ssl/include OPENSSL_LIB_PATH=/usr/local/ssl/lib
      ./zcutil/build.sh -j2
      cp $SNAPCRAFT_PART_BUILD/src/safecoind $SNAPCRAFT_PART_INSTALL/bin/
      cp $SNAPCRAFT_PART_BUILD/contrib/debian/examples/safecoin.conf $SNAPCRAFT_PART_INSTALL/.safecoin/

apps:
  safecoin:
    command: bin/safecoind
    plugs: [home, network, network-bind]
    #daemon: simple
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:/var/lib/snapd/desktop:$XDG_DATA_DIRS
      home: $SNAP_USER_COMMON
      # Override HOME so the datadir is located at
      # ~/snap/safecoin/common/.safecoin/ see Denarius snapcraft.yaml for more info
      # have to figure out how to maybe use echo or cat to create a safecoin.conf and have to figure out how to download zcash params and put them in correct location
  cli:
    command: bin/safecoin-cli
    plugs: [home, network, network-bind]
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:/var/lib/snapd/desktop:$XDG_DATA_DIRS
      home: $SNAP_USER_COMMON